# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quality.IssueResolution'),
        ),
    ]
