# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_auto_20170827_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('dateLoaded', models.DateTimeField()),
                ('imported', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('dateImported', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('dateProcessed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
