# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_issueprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=100)),
                ('informer', models.CharField(max_length=100)),
                ('assignee', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('reproducibility', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('resume', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.IssueProcess')),
            ],
        ),
    ]
