# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20170830_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueinput',
            name='comments',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issueinput',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
