# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_auto_20170830_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueinput',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
