# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_auto_20170830_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueprocess',
            name='inserted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issueprocess',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
    ]
